## Урок 6. Домашнее задание.

### Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from scipy import stats

### Задача 6.1

Даны значения величины заработной платы заемщиков банка (`salary`) и значения их поведенческого кредитного скоринга (`scoring`):
```
salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]
```
1. Найдите ковариацию этих двух величин: сначала без использования специальных функций, а затем с помощью функции `numpy.cov`. Полученные значения должны быть равны.
2. Найдите коэффициент корреляции Пирсона: с помощью ковариации и средних квадратических отклонений двух признаков, а затем с помощью специальных функций из библиотек `numpy` и `pandas`.

#### Решение:

1. Ковариация

In [2]:
salary = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
scoring = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [3]:
X = salary
Y = scoring

MX = X.mean()
MY = Y.mean()

Формула ковариации случайных величин $X$ и $Y$:

$\operatorname{cov}(X, Y) = M\left( (X - M(X)) (Y - M(Y)) \right).$

In [4]:
cov = ((X - MX) * (Y - MY)).sum() / (X.shape[0] - 1)
cov

10175.37777777778

In [5]:
cov = np.cov(X, Y)
cov

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

2. Корреляция

In [6]:
corr = cov / (X.std(ddof=1) * Y.std(ddof=1))
corr

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [7]:
np.corrcoef(X, Y)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Задача 6.2

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:
```
131, 125, 115, 122, 131, 115, 107, 99, 125, 111
```
Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

#### Решение:

Так как нам неизвестны дисперсия и сигма генеральной совокупности, то вычислять будем через квантили Стьюдента

In [8]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = iq.shape[0]

Найдем t квантиль:

In [9]:
t = stats.t.ppf(1 - 0.05 / 2, n - 1)
t

2.2621571627409915

Найдем несмещенное среднеквадратичное отклонение:

In [10]:
s = iq.std(ddof=1)
s

10.54566788359614

и выборочное среднее:

In [11]:
m = iq.mean()
m

118.1

По формуле
$
P \left( 
\overline{X} - t_{1 - \alpha/2, \: n - 1} \cdot \dfrac{S}{\sqrt{n}} 
\leq M(X) \leq
\overline{X} + t_{1 - \alpha/2, \: n - 1} \cdot \dfrac{S}{\sqrt{n}} 
\right) = 1 - \alpha,
$

вычислим доверительный интервал:

In [12]:
(m - t * s / np.sqrt(n), m + t * s / np.sqrt(n))

(110.55608365158724, 125.64391634841274)

### Задача 6.3

Известно, что рост футболистов в сборной распределен нормально с известной дисперсией 25. На выборке объёма 27 выборочное среднее составило 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

#### Решение:

Дисперсия сразу известна и доверительный интервал равен 0.95 поэтому решается нормлаьным распределением по правилу двух сигм:

In [13]:
DX = 25
n = 27
m = 174.2

In [14]:
s = np.math.sqrt(DX/n)
s

0.9622504486493763

Доверительный интервал для математического ожидания с надежностью 0.95 равен:

In [15]:
(m - 2 * s, m + 2 * s)

(172.27549910270125, 176.12450089729873)